app:
  port: {{APP_PORT}}
  url: {{APP_URL}}

sls:
  POOL_REGION: {{SLS_POOL_REGION}}
  SLS_ACCESS_KEY: {{SERVERLESS_ACCESS_KEY}}
  SLS_SECRET_KEY: {{SERVERLESS_SECRET_KEY}}
  SLS_USERPOOL_ID: {{SLS_USERPOOL_ID}}
  SLS_USERPOOL_CLIENT_ID: {{SLS_USERPOOL_CLIENT_ID}}
  S3_BUCKET_NAME: {{S3_BUCKET_NAME}}
  CLOUDFRONT_URL: {{CLOUDFRONT_URL}}
  DB_SERVICE_SELECT: SELECT
  DB_SERVICE_INSERT: INSERT
  DB_SERVICE_UPDATE: UPDATE
  DB_SERVICE_DELETE: DELETE
  DB_SERVICE_COUNT: COUNT
  DB_SERVICE_FUNCTION: {{DB_SERVICE_FUNCTION}}
  DB_SSO: {{DB_SSO}}
  MAIL_SERVICE: {{MAIL_SERVICE}}

token:
  KEY: {{TOKEN_KEY}}